language: node_js
node_js:
- '0.12'
- '0.11'
- iojs-v1
- iojs-v2
script: npm test
before_script:
- npm install
after_success:
- ./node_modules/coveralls/bin/coveralls.js < ./lcov.info
deploy:
  provider: npm
  email: fam-operations@freeallmedia.com
  api_key:
    secure: FlR0JEINalLqrGdN7uECPp3Qpmrpt2Bmrf6ognWjwsu9LVUkq/k8CtmucgEFrta3tvZnU0vq7Z3NOJwDZPKdpTLnO0+NsMOa/LeZIg3YoA9N8C8/Gg8w7XNWkMZLXeAtuuyS/Y3JH5QLlcXxIs904ouBZ0fvc7oquDeIwlUmiOmdGo2ekHWKeRsg5kQHKXA/JdItlwFv4lSL8c0BKgurkiyC67+baJGBp+5cIKPabypXSKD7ItHhWXpJxrBNUqCJ9MHfwLsfiux9S5Fe47H92ISunsFdmHosuF1Awe2cHZXQxMeKj5k4VZGTh8EJEPloYe6q5AXSgGFwY/UL65NAMwemM2H6AlQZTIxmLlKGlT7Foh1iiiAxqXMWNnVZPxUR7R01cGSkJs/+Lv7Wv6OCO/BiCcuPqRGddlEsL9eGuDpuMjniLFqMeRBycZZnEiM6yXKEsJlzAlDLLsbPoUVLKP/qkiCLBpzi6TtP44bKaQ4WAF/LldHDEnfvPbPaaBkJtunVdM/2ie1BdAIa4cQweyGt8BAqxOp5PxA+2qTc99JMw1c0vuxqF56BmT2dwDSJi+/iGskd9vVG7pnlrk/oxlM0T0bK+tmJYcZgkFwZAwzLZFLVZM2YxaoglzUphUe7s28KZ9QFthF7C+aqcQWhpJz06j4OZbKyXf+D7fQT5BM=
  on:
    repo: FreeAllMedia/generator-forbin-scudl
    branch: master
